version: '3.1'

services:
  generator:
    image: my-registry:55000/gen:ci-20
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
  integration:
    image: my-registry:55000/gen:integration-20
    build: .